### ISSUE TITLE
error at the installation 

### ISSUE THREAD

**Issue by xattack** [roothaxor/PyStat#1]
![screenshot from 2017-08-16 11-42-19](https://user-images.githubusercontent.com/8902460/29374778-4b28cdda-8278-11e7-9e68-20d86811d97c.png)

error at the installation on windows 7

**Comment by roothaxor** [comment]
python version you are using ?

**Comment by roothaxor** [comment]
Install script generates a .bat file here is content of the pystat.bat
"@echo off
python C:\tools\pystat\pystat_core.py
pause"
You should Change C:\tools\pystat\ to your directory location of pystat and save it as pystat.bat then copy it to C:\windows\ directory ( which will add pystat in command line like alias in linux )

Modules to install:
termcolor, colorama

**Comment by d3c0d3d** [comment]
![error_install_in_python3 6 2](https://user-images.githubusercontent.com/29043805/29498188-4d0cc7a2-85cd-11e7-94b1-e56369db081c.PNG)

I had just installed [python 3](https://chocolatey.org/packages/python3), when I went to run I got the same error as the friend just above!

**Comment by roothaxor** [comment]
Sorry, but this is for Version 2. i'll add this information in README

**Comment by d3c0d3d** [comment]
Thanks for the feedback!
