### ISSUE TITLE
If using MobaXterm as environment on Windows 7 also gets erros on installation 

### ISSUE THREAD

**Issue by xattack** [roothaxor/PyStat#2]
If using MobaXterm as environment on Windows 7 also gets erros on installation 

![screenshot from 2017-08-16 12-04-36](https://user-images.githubusercontent.com/8902460/29375688-839775a6-827b-11e7-8311-867acadcf5a5.png

**Comment by roothaxor** [comment]
i dont have idea of MobaXterm environment, sorry!
